set(_AMENT_PACKAGE_NAME "dex_hand_ros2")
set(dex_hand_ros2_VERSION "0.2.0")
set(dex_hand_ros2_MAINTAINER "Yuan Lei <u3650775@connect.hku.hk>")
set(dex_hand_ros2_BUILD_DEPENDS "rclpy" "std_msgs" "std_srvs")
set(dex_hand_ros2_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_python" "rosidl_default_generators")
set(dex_hand_ros2_BUILD_EXPORT_DEPENDS "rclpy" "std_msgs" "std_srvs")
set(dex_hand_ros2_BUILDTOOL_EXPORT_DEPENDS )
set(dex_hand_ros2_EXEC_DEPENDS "rosidl_default_runtime" "python3-serial" "rclpy" "std_msgs" "std_srvs")
set(dex_hand_ros2_TEST_DEPENDS "ament_cmake_pytest" "python3-pytest")
set(dex_hand_ros2_GROUP_DEPENDS )
set(dex_hand_ros2_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(dex_hand_ros2_DEPRECATED "")
set(dex_hand_ros2_EXPORT_TAGS)
list(APPEND dex_hand_ros2_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
